### PR TITLE
versifier key-value structure panic fix and parsing order

### LINKED ISSUE #55: fuzzing github.com/andybalholm/cascadia crashes versifier
When I try to fuzz the CSS selector parsing code in github.com/andybalholm/cascadia, I get the following panic:

panic: runtime error: slice bounds out of range

goroutine 28 [running]:
github.com/dvyukov/go-fuzz/go-fuzz/versifier.structureKeyValue(0xc820328180, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:696 +0x489
github.com/dvyukov/go-fuzz/go-fuzz/versifier.structure(0xc820328180, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:575 +0xdd
github.com/dvyukov/go-fuzz/go-fuzz/versifier.BuildVerse(0xc82027a1b0, 0xc82020a960, 0x6, 0x6, 0x10000)
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:55 +0x1b9
main.(*Hub).loop(0xc820224100)
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:236 +0x1c2c
created by main.newHub
	/Users/andy/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:115 +0xe83

### PR DESCRIPTION
**Pull request by rlmcpherson**
This should fix #55. It also allows parsing of key-value lists and key-value nodes within bracket nodes.

### CODE REVIEW

File: go-fuzz/versifier/versifier.go [hunk 1]
```diff
@@ -571,8 +571,8 @@ func tokenize(data []byte) []Node {
 func structure(nn []Node) []Node {
 	nn = extractNumbers(nn)
 	nn = structureBrackets(nn)
-	nn = structureLists(nn)
 	nn = structureKeyValue(nn)
+	nn = structureLists(nn)
```
Comment (dvyukov) [inline go-fuzz/versifier/versifier.go]: Why is this better?
There can be lists of kv and kv with lists. For example, http headers can be kv with lists in value.

**Comment by rlmcpherson** [comment]
Currently the KeyValueNode is defined as 

```
type KeyValNode struct {
	delim rune
	key   *AlphaNumNode
	value *AlphaNumNode
}
```

so kv with lists won't be parsed correctly anyway. If it is made more general, though, to include other types of nodes in key-value values, those should be parseable. I'll try to change the KeyValNode and parsing to handle that scenario.
