### PR TITLE
go-fuzz-build: fix Windows build

### LINKED ISSUE #224: libFuzzer support may have broken or at least altered Windows support
I am not sure if this is 1 issue or 2 issues, or perhaps user error, but it seems `go-fuzz-build` now fails with error `build output ... already exists and is not an object file` on Windows.

These steps currently fail on Windows with the latest version of dvyukov/go-fuzz:
```
set CGO_ENABLED=0
set GOPATH=C:\temp\gopath-go-fuzz-master
set PATH=%GOPATH%\bin;%PATH%
go get -u github.com/dvyukov/go-fuzz/...
go get -v -d github.com/dvyukov/go-fuzz-corpus/png
cd %GOPATH%/src/github.com/dvyukov/go-fuzz-corpus
cd png
go-fuzz-build
```
`go-fuzz-build` fails with error:
```
failed to execute go build: exit status 1
go build github.com/dvyukov/go-fuzz-corpus/png/go.fuzz.main: 
 build output "C:\\Users\\...\\AppData\\Local\\Temp\\go-fuzz863067130"
 already exists and is not an object file
```

If you do the same steps but without `set CGO_ENABLED=0`, it instead fails with:

```
could not load standard library: go [list -e -json -compiled -test=false -export=false -deps=false -find=true -- std]: exit status 2: # runtime/cgo
exec: "gcc": executable file not found in %PATH%
```

I suspect CGO_ENABLED / gcc issue might be a separate issue from `build output ... already exists and is not an object file` issue.

The 2019-03-04 version at commit b73ac4d3ed from just before the libFuzzer work seems to function properly on Windows (here still setting CGO_ENABLED=0 to avoid complaints about gcc):

```
set CGO_ENABLED=0
set GOPATH=C:\temp\gopath-go-fuzz-2019-03-04-b73ac4d3ed
set PATH=%GOPATH%\bin;%PATH%
go get -u github.com/dvyukov/go-fuzz/...
go get -v -d github.com/dvyukov/go-fuzz-corpus/png
cd %GOPATH%/src/github.com/dvyukov/go-fuzz
git checkout b73ac4d3ed
go install ./...
cd %GOPATH%/src/github.com/dvyukov/go-fuzz-corpus
cd png
go-fuzz-build
go-fuzz
```

<pre>
$ go version
go version go1.12 windows/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\...\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\temp\gopath-go-fuzz-master
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\...\Temp\go-build648862030=/tmp/go-build -gno-record-gcc-switches

</pre></details>

CC @josharian

### PR DESCRIPTION
**Pull request by josharian**
Windows does not allow you to overwrite an existing file during 'go build'.

@thepudds can you confirm that this fixes #224?

### CODE REVIEW

File: go-fuzz-build/main.go [hunk 1]
```diff
@@ -325,6 +325,9 @@ func (c *Context) buildInstrumentedBinary(blocks *[]CoverBlock, sonar *[]CoverBl
 	c.instrumentPackages(blocks, sonar)
 	mainPkg := c.createFuzzMain()
 	outf := c.tempFile()
+	if runtime.GOOS == "windows" {
+		os.Remove(outf)
```
Comment (dvyukov) [inline go-fuzz-build/main.go]: Do we rely on `c.tempFile()` result being an existent file anywhere else? If not we could remove it right in `tempFile`, which would be cleaner then polluting higher-level functions with OS-dependent quirks.

**Comment by thepudds** [comment]
@josharian Your current change does seem to fix the `build output ... already exists and is not an object file` error on Windows from #224.  

Also, good chance you already saw this, but PR #228 with initial travis support was merged earlier today if you want to see what travis has to say about this.  ;-)

**Comment by josharian** [comment]
Hurray for travis!

**Comment by thepudds** [comment]
Master looks green now in travis!

https://travis-ci.org/dvyukov/go-fuzz/builds/508667718
